### ISSUE TITLE
Compiling under DOS/DJGPP

### ISSUE THREAD

**Issue by MaiRat** [ghaerr/microwindows#135]
Hi,

currently, the DOS/DJGPP Build is broken (cannot find Gd* - functions, GdCreatePixmap, GdError). I tried commit by commit and here is the faulting commit:

https://github.com/ghaerr/microwindows/commit/0b82fa8056f4c2609fa7a372dada093a23e866dd

Can you please look, what cause the errors?

Thank you!

**Comment by ghaerr** [comment]
Hi @MaiRat,

Thanks for reporting this. I don't have DJGPP setup in order to test, however your debugging finding the offending commit helps a lot. Can you post the compilation error output in a file or .zip so I can take a look at it? That will help speed getting this back working for you.

Thank you!

**Comment by ghaerr** [comment]
It appears that the engine/*.o files are not being included in the -lmwin library which is created at e:microwin/src/lib/libmwin.a.

It is quite hard for me to debug since I cannot run the DJGPP compiler on macOS over here. I would suggest we start by displaying what is in libmwin.a using something like:
```
ar tv e:microwin/src/lib/libmwin.a
```
This will show whether the Gd* routines are included, which they should be. Your `make` output shows that src/engine/*.o is included, but it might be they were not compiled.

The next thing to check is whether the engine routines are in a separate lib/libmengine.a, which can be checked to see if exists, and then run `ar tv` to display. If that library exists, then perhaps changing the following lines in Makefile_nr:
```
ifdef MICROWIN
LIBS += -lmwin -limages $(CLIBS) $(EXTENGINELIBS)
endif
```
to
```
ifdef MICROWIN
LIBS += -lmwin -lmwengine -limages $(CLIBS) $(EXTENGINELIBS)
endif
```
If none of this works, then we need to determine whether the Makefile_nr instructions for creating the libraries are working. I see the engine files being compiled in your error scripts, but can't seem to figure out why the .o files are not in libmwin.a.

Another possibility is that the e: prefix is confusing the Makefile, in the following lines, which do not included the e: prefix:
```
ALL += drivers/libmwdrivers.a fonts/libfonts.a engine/libmwengine.a nanox/libnano-X.a
```
If that is the case, perhaps try doing the make without having an explicit e: prefix.

I am sorry I cannot reproduce the problem to allow us to quickly identify the problem. I would like to see the contents of the microwin/src/lib directory if all else fails.

**Comment by ghaerr** [comment]
Update: I realized that macOS is supported using Makefile_nr by using:
```
$ make -f Makefile_nr ARCH=MACOS clean
$ make -f Makefile_nr ARCH=MACOS
```
This properly builds the Microwindows on my system.

The macOS build follows the same paths as building for DJGPP, for which I presume you're using:
```
$ make -f Makefile_nr ARCH=CROSSDOS clean
$ make -f Makefile_nr ARCH=CROSSDOS
```
Thus, I believe the issue is likely to do with Makefile_nr not properly handling a drive prefix (e.g. e:) in the build. Can you retry the build using the second set of commands above, but instead of using the make's default CURDIR which includes the drive letter, setting it directly in the top line of Makefile_nr, like this:
```
CURDIR = /microwin/src
```
If this works, then the fix will probably be to remove any drive prefix from the automatically set CURDIR variable, since various `$(addprefix ...)` operations are performed within the Makefiles, which likely won't work with drive letters also prefixed.

**Comment by MaiRat** [comment]
First, thank you for the great project and for your support! :-)

Second: the ar command prints out, that following object files are missing from libmwin.a:

fb.o
fblin1.o
fblin16.o
fblin2.o
fblin24.o
fblin32.o
fblin4.o
fblin8.o
fbportrait_down.o
fbportrait_left.o
fbportrait_right.o
genfont.o
genmem.o
kbd_dj.o
mou_dos.o
osdep.o
rasterops.o

Complete elimination of prefix e: doesnt make any difference. A libmwengine file doesnt exist.
